# Generated by Django 5.0.6 on 2024-07-12 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='portrait_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_portraits', to='api.file'),
        ),
    ]
