# Generated by Django 5.0.7 on 2024-07-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_portrait_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='autor',
            field=models.TextField(blank=True, default='Autor desconocido', null=True),
        ),
    ]
