# Generated by Django 5.0.7 on 2024-07-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_reference_autor"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="titulo",
            field=models.TextField(blank=True, default="Sin titulo", null=True),
        ),
    ]
